FROM golang:latest AS builder

RUN mkdir /whitemos
WORKDIR /whitemos
ENV GO111MODULE=on 

COPY go.mod . 
COPY go.sum .
RUN go mod download

COPY . .

RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build

FROM alpine:latest
RUN apk update && \
    apk upgrade && \
    apk add --no-cache curl && \
    rm -rf /var/cache/apk/* && \
    mkdir -p /jasonsoft/whitemos

COPY --from=builder /whitemos/whitemos /jasonsoft/whitemos/whitemos 
COPY --from=builder /whitemos/views /jasonsoft/whitemos/views
COPY --from=builder /whitemos/public /jasonsoft/whitemos/public
WORKDIR /jasonsoft/whitemos
CMD ./whitemos

