FROM golang:1.8.3
COPY . /go/src/github.com/jasonsoft/whitemos/
WORKDIR /go/src/github.com/jasonsoft/whitemos
RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build

FROM alpine:3.6
RUN apk update && \
    apk upgrade && \
    apk add --no-cache curl && \
    rm -rf /var/cache/apk/* && \
    mkdir -p /jasonsoft/whitemos

COPY --from=0 /go/src/github.com/jasonsoft/whitemos/whitemos /jasonsoft/whitemos/whitemos
WORKDIR /jasonsoft/whitemos
CMD ./whitemos

HEALTHCHECK --interval=5s --timeout=10s CMD curl -f http://localhost/health || exit 1
