FROM golang:1.10 AS builder
COPY . /go/src/github.com/jasonsoft/whitemos/
WORKDIR /go/src/github.com/jasonsoft/whitemos
RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build

FROM alpine:3.7
RUN apk update && \
    apk upgrade && \
    apk add --no-cache curl && \
    rm -rf /var/cache/apk/* && \
    mkdir -p /jasonsoft/whitemos

COPY --from=builder /go/src/github.com/jasonsoft/whitemos/whitemos /jasonsoft/whitemos/whitemos 
COPY --from=builder /go/src/github.com/jasonsoft/whitemos/views /jasonsoft/whitemos/views
COPY --from=builder /go/src/github.com/jasonsoft/whitemos/public /jasonsoft/whitemos/public
WORKDIR /jasonsoft/whitemos
CMD ./whitemos

